//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace onlineSinavPortali.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Soru
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Soru()
        {
            this.Secenek = new HashSet<Secenek>();
        }
    
        public int soruId { get; set; }
        public string soruMetin { get; set; }
        public Nullable<int> soruSinavId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Secenek> Secenek { get; set; }
        public virtual Sinav Sinav { get; set; }
    }
}
